### ISSUE TITLE
CONCERN: Re-rendering all elements in a list every time it is mutated.

### ISSUE THREAD

**Issue by JaymanMDev** [benbraide/InlineJS#1]
Hey, I am liking the look of this library, and the idea. However, I am a bit disappointed that rendering lists isn't as efficient as I would have hoped.

This isn't a bug report, or an issue of any kind. I just hope that list rendering is improved at some point :)

Thankyou!

**Comment by JaymanMDev** [comment]
Also, another thing. Is it possible for you to turn this into an npm package. It is a little bit of a pain to download all of the libraries/add-ons separately. :)

**Comment by benbraide** [comment]
> Hey, I am liking the look of this library, and the idea. However, I am a bit disappointed that rendering lists isn't as efficient as I would have hoped.

Thanks for your interest. The `x-each` directive, together with a unique `:key` improves on the efficiency and only re-render items that are new or removed from the list

**Comment by JaymanMDev** [comment]
> > Hey, I am liking the look of this library, and the idea. However, I am a bit disappointed that rendering lists isn't as efficient as I would have hoped.
> 
> Thanks for your interest. The `x-each` directive, together with a unique `:key` improves on the efficiency and only re-render items that are new or removed from the list

Ahhh, that makes sense! Thanks :)
